-- DATA CLEANING 

USE WORLD_LAYOFFS;

SELECT * 
FROM LAYOFFS;

---

-- 1.  REMOVE DUPLICATES
-- 2. STANDARDIZE THE DATA
-- 3. REMOVE NULLS , BLANKS 
-- 4. DROP UNWANTED COLUMNS 

-- 


CREATE TABLE LAYOFFS_STAGGING
LIKE LAYOFFS;



INSERT INTO  LAYOFFS_STAGGING
SELECT * FROM LAYOFFS;

SELECT *
FROM  LAYOFFS_STAGGING;




SELECT *, ROW_NUMBER() OVER(PARTITION BY 
COMPANY, LOCATION,INDUSTRY,TOTAL_LAID_OFF,PERCENTAGE_LAID_OFF,`DATE`,STAGE,COUNTRY,FUNDS_RAISED_MILLIONS) AS ROW_NUM
FROM LAYOFFS_STAGGING;



WITH DUPLICATE_CTE AS
(
SELECT *, ROW_NUMBER() OVER(PARTITION BY 
COMPANY, LOCATION,INDUSTRY,TOTAL_LAID_OFF,PERCENTAGE_LAID_OFF,`DATE`,STAGE,COUNTRY,FUNDS_RAISED_MILLIONS) AS ROW_NUM
FROM LAYOFFS_STAGGING
)
SELECT *
FROM DUPLICATE_CTE
WHERE ROW_NUM > 1;





CREATE TABLE `layoffs_stagging2` (
  `company` text,
  `location` text,
  `industry` text,
  `total_laid_off` int DEFAULT NULL,
  `percentage_laid_off` text,
  `date` text,
  `stage` text,
  `country` text,
  `funds_raised_millions` int DEFAULT NULL,
  `ROW_NUM` INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



SELECT *
FROM layoffs_stagging2;

INSERT INTO layoffs_stagging2
SELECT *, ROW_NUMBER() OVER(PARTITION BY 
COMPANY, LOCATION,INDUSTRY,TOTAL_LAID_OFF,PERCENTAGE_LAID_OFF,`DATE`,STAGE,COUNTRY,FUNDS_RAISED_MILLIONS) AS ROW_NUM
FROM LAYOFFS_STAGGING;

SELECT *
FROM layoffs_stagging2
WHERE ROW_NUM >1;


SET SQL_SAFE_UPDATES = 0;


DELETE
FROM layoffs_stagging2
WHERE ROW_NUM >1;

SELECT *
FROM layoffs_stagging2;



-- STANDARDIZING DATA 


SELECT COMPANY , TRIM(COMPANY)
FROM LAYOFFS_STAGGING2;


UPDATE LAYOFFS_STAGGING2
SET COMPANY = TRIM(COMPANY);

SELECT * 
FROM LAYOFFS_STAGGING2
;




SELECT * 
FROM LAYOFFS_STAGGING2
WHERE INDUSTRY LIKE "CRYPTO%";


UPDATE LAYOFFS_STAGGING2
SET INDUSTRY = 'Crypto'
WHERE INDUSTRY LIKE "CRYPTO%";



SELECT DISTINCT COUNTRY
FROM LAYOFFS_STAGGING2
ORDER BY 1;



SELECT DISTINCT COUNTRY , TRIM(TRAILING '.' FROM COUNTRY)
FROM LAYOFFS_STAGGING2
ORDER BY 1;


UPDATE LAYOFFS_STAGGING2
SET COUNTRY = TRIM(TRAILING ',' FROM COUNTRY)
WHERE COUNTRY LIKE 'UNITED STATES%';



SELECT `DATE`, STR_TO_DATE(`date`,'%m/%d/%Y')
FROM LAYOFFS_STAGGING2;


UPDATE LAYOFFS_STAGGING2
SET `DATE` = STR_TO_DATE(`date`,'%m/%d/%Y');



SELECT * FROM LAYOFFS_STAGGING2;


ALTER TABLE LAYOFFS_STAGGING2
MODIFY COLUMN `date` DATE;


SELECT * FROM LAYOFFS_STAGGING2;



SELECT * FROM LAYOFFS_STAGGING2
WHERE TOTAL_LAID_OFF IS NULL AND PERCENTAGE_LAID_OFF IS NULL;



SELECT * 
 FROM LAYOFFS_STAGGING2
 WHERE INDUSTRY IS NULL
 OR INDUSTRY = '';

SELECT *
FROM LAYOFFS_STAGGING2
WHERE COMPANY = "Airbnb";



UPDATE LAYOFFS_STAGGING2
SET INDUSTRY = NULL
WHERE INDUSTRY = '';



SELECT T1.INDUSTRY,T2.INDUSTRY
FROM LAYOFFS_STAGGING2 T1
JOIN LAYOFFS_STAGGING2 T2
ON T1.COMPANY = T2.COMPANY 
WHERE (T1.INDUSTRY IS NULL OR T1.INDUSTRY = '')
AND T2.INDUSTRY IS NOT NULL;



UPDATE LAYOFFS_STAGGING2 T1
JOIN LAYOFFS_STAGGING2 T2
ON T1.COMPANY = T2.COMPANY 
SET T1.INDUSTRY = T2.INDUSTRY
WHERE (T1.INDUSTRY IS NULL OR T1.INDUSTRY = '')
AND T2.INDUSTRY IS NOT NULL;


SELECT *
FROM LAYOFFS_STAGGING2;


DELETE
FROM LAYOFFS_STAGGING2
WHERE TOTAL_LAID_OFF IS NULL AND PERCENTAGE_LAID_OFF IS NULL;


ALTER TABLE LAYOFFS_STAGGING2
DROP COLUMN ROW_NUM;









